/* eslint-disable @typescript-eslint/no-require-imports */
// assets/avatars.ts
const avatars = {
  a1: require("./avatars/a1.png"),
  a2: require("./avatars/a2.png"),
  a3: require("./avatars/a3.png"),
  a4: require("./avatars/a4.png"),
  a5: require("./avatars/a5.png"),
  a6: require("./avatars/a6.png"),
  a7: require("./avatars/a7.png"),
  a8: require("./avatars/a8.png"),
  a9: require("./avatars/a9.png"),
  a10: require("./avatars/a10.png"),
  a11: require("./avatars/a11.png"),
  a12: require("./avatars/a12.png"),
  a13: require("./avatars/a13.png"),
  a14: require("./avatars/a14.png"),
  a15: require("./avatars/a15.png"),
  a16: require("./avatars/a16.png"),
  a17: require("./avatars/a17.png"),
  a18: require("./avatars/a18.png"),
  a19: require("./avatars/a19.png"),
  a20: require("./avatars/a20.png"),
  a21: require("./avatars/a21.png"),
  a22: require("./avatars/a22.png"),
  a23: require("./avatars/a23.png"),
  a24: require("./avatars/a24.png"),
  a25: require("./avatars/a25.png"),
  a26: require("./avatars/a26.png"),
  a27: require("./avatars/a27.png"),
  a28: require("./avatars/a28.png"),
  a29: require("./avatars/a29.png"),
  a30: require("./avatars/a30.png"),
  a31: require("./avatars/a31.png"),
  a32: require("./avatars/a32.png"),
  a33: require("./avatars/a33.png"),
  a34: require("./avatars/a34.png"),
  a35: require("./avatars/a35.png"),
  a36: require("./avatars/a36.png"),
  a37: require("./avatars/a37.png"),
  a38: require("./avatars/a38.png"),
  a39: require("./avatars/a39.png"),
  a40: require("./avatars/a40.png"),
  a41: require("./avatars/a41.png"),
  a42: require("./avatars/a42.png"),
  a43: require("./avatars/a43.png"),
  a44: require("./avatars/a44.png"),
  a45: require("./avatars/a45.png"),
  a46: require("./avatars/a46.png"),
  a47: require("./avatars/a47.png"),
  a48: require("./avatars/a48.png"),
  a49: require("./avatars/a49.png"),
  a50: require("./avatars/a50.png"),
  a51: require("./avatars/a51.png"),
  a52: require("./avatars/a52.png"),
  a53: require("./avatars/a53.png"),
  a54: require("./avatars/a54.png"),
  a55: require("./avatars/a55.png"),
  a56: require("./avatars/a56.png"),
  default: require("./avatars/default.png"),
};

export type AvatarId = keyof typeof avatars;
export default avatars;

export const getAvatarImage = (id?: string) => {
  return avatars[id as AvatarId] ?? avatars["default"];
};
